// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9A_YPmwN0cl_XD4TuZ1x1ukmG2wCgPRc',
    appId: '1:991291663420:web:4c2e58de7e3ceee1f30f39',
    messagingSenderId: '991291663420',
    projectId: 'bablecash',
    authDomain: 'bablecash.firebaseapp.com',
    storageBucket: 'bablecash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNGnAL0dFJAegk_PYFJODXRiRV2kAX3Q',
    appId: '1:991291663420:android:4a48dd17e920a4c1f30f39',
    messagingSenderId: '991291663420',
    projectId: 'bablecash',
    storageBucket: 'bablecash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ERosnJS68t_2TO9q2HIKQbzlNdsn_Pk',
    appId: '1:991291663420:ios:1bdd5bdfa2f69b98f30f39',
    messagingSenderId: '991291663420',
    projectId: 'bablecash',
    storageBucket: 'bablecash.appspot.com',
    iosBundleId: 'com.example.babylon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ERosnJS68t_2TO9q2HIKQbzlNdsn_Pk',
    appId: '1:991291663420:ios:1bdd5bdfa2f69b98f30f39',
    messagingSenderId: '991291663420',
    projectId: 'bablecash',
    storageBucket: 'bablecash.appspot.com',
    iosBundleId: 'com.example.babylon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9A_YPmwN0cl_XD4TuZ1x1ukmG2wCgPRc',
    appId: '1:991291663420:web:c2760c948f4572c0f30f39',
    messagingSenderId: '991291663420',
    projectId: 'bablecash',
    authDomain: 'bablecash.firebaseapp.com',
    storageBucket: 'bablecash.appspot.com',
  );

}