// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3JJLmy_NCrv8fpHKismnfLPmEFkzTvE',
    appId: '1:537015197086:web:bf0c4c185be1c5e2f10a8f',
    messagingSenderId: '537015197086',
    projectId: 'babl-cash',
    authDomain: 'babl-cash.firebaseapp.com',
    storageBucket: 'babl-cash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OGWrZqXka2dHj81JOVm96jGaR-pl7Nk',
    appId: '1:537015197086:android:43f6ef35a390f5b7f10a8f',
    messagingSenderId: '537015197086',
    projectId: 'babl-cash',
    storageBucket: 'babl-cash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJtR0WbaZWNbsS9y-8qckx2gBjD6FrcQ',
    appId: '1:537015197086:ios:f428f805e6664ce6f10a8f',
    messagingSenderId: '537015197086',
    projectId: 'babl-cash',
    storageBucket: 'babl-cash.appspot.com',
    iosClientId: '537015197086-b627pef1ps8j3ulre2pis2p2i2ovfupn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggggg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhJtR0WbaZWNbsS9y-8qckx2gBjD6FrcQ',
    appId: '1:537015197086:ios:f428f805e6664ce6f10a8f',
    messagingSenderId: '537015197086',
    projectId: 'babl-cash',
    storageBucket: 'babl-cash.appspot.com',
    iosClientId: '537015197086-b627pef1ps8j3ulre2pis2p2i2ovfupn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggggg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu3JJLmy_NCrv8fpHKismnfLPmEFkzTvE',
    appId: '1:537015197086:web:06d73d7dcef18d16f10a8f',
    messagingSenderId: '537015197086',
    projectId: 'babl-cash',
    authDomain: 'babl-cash.firebaseapp.com',
    storageBucket: 'babl-cash.appspot.com',
  );

}